import {tokens as base} from './tokens';
import {paperTheme} from './paperTheme';
// Hallmark: studied reference — Keitoto Conversation & Response Flow.
// Native adaptation: centered welcome, compact prompt cards, open transcript.
export const chatTokens = {
  ...base,
  chat: {
    ...base.chat,
    headerHeight: 56,
    headerAction: 40,
    indicatorWidth: 4,
    indicatorHeight: 4,
    brandSize: 17,
    brandTracking: -0.3,
    emptyTitle: 27,
    emptyLine: 37,
    gutter: 20,
    messageGap: 24,
    composerElevation: 2,
    composerShadowOpacity: 0.08,
    composerShadowRadius: 12,
    composerShadowOffset: 4,
    surfaceElevation: 1,
    surfaceShadowOpacity: 0.16,
    surfaceShadowRadius: 9,
    surfaceShadowOffset: 3,
    raisedScale: 0.985,
    entranceDistance: 10,
    entranceDuration: 420,
    welcomeMark: 64,
    welcomeMaxWidth: 360,
    welcomeBottomSpace: 64,
    cardHeight: 86,
    promptHeight: 40,
    promptIcon: 15,
    title1: 23,
    title2: 20,
    title3: 18,
    bodyLine: 26,
  },
} as const;
export const chatTheme = {
  ...paperTheme,
  colors: {
    ...paperTheme.colors,
    primary: chatTokens.color.primary,
    primaryContainer: chatTokens.color.primaryMuted,
    onPrimaryContainer: chatTokens.color.primaryPressed,
    background: chatTokens.color.canvas,
    surface: chatTokens.color.surface,
    surfaceVariant: chatTokens.color.surfaceMuted,
    onSurface: chatTokens.color.ink,
    onSurfaceVariant: chatTokens.color.body,
    outline: chatTokens.color.border,
    outlineVariant: chatTokens.color.border,
  },
};
