export const tokens = {
  color: {
    canvas: '#F6F5FA',
    atmosphereTop: '#E8E3FA',
    atmosphereMiddle: '#F0EDF9',
    surface: '#FFFFFF',
    surfaceMuted: '#EEEEF3',
    ink: '#111118',
    body: '#464652',
    muted: '#6C6C7B',
    border: '#DDDDE6',
    shadowSoft: '#CBC6DE',
    scrim: 'rgba(17, 17, 24, 0.24)',
    primary: '#7563EE',
    primaryPressed: '#493BA6',
    primaryMuted: '#EFEDFC',
    onPrimary: '#FFFFFF',
    error: '#BE222A',
    errorSoft: '#FCEBEC',
  },
  launch: {
    orbSize: 96,
    initialScale: 0.92,
    arriveDuration: 600,
    minimumDuration: 850,
    exitDuration: 260,
  },
  motion: {loadingMinimum: 450},
  font: {displayIOS: 'Georgia', displayAndroid: 'serif'},
  composer: {
    frameRadius: 16,
    panelRadius: 12,
    inset: 4,
    caption: 11,
    icon: 18,
    action: 32,
    row: 44,
    attachmentRow: 36,
    gap: 6,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: 2,
    elevation: 1,
  },
  space: {xxs: 4, xs: 8, sm: 12, md: 16, lg: 24, xl: 32, xxl: 48},
  radius: {sm: 8, md: 12, lg: 16, full: 999},
  size: {touch: 48, composer: 56},
  chat: {
    maxWidth: 680,
    headerHeight: 64,
    gutter: 20,
    messageGap: 28,
    brandSize: 21,
    brandTracking: -0.6,
    emptyTitle: 28,
    emptyLine: 36,
    line: 24,
    icon: 22,
    mark: 28,
    rule: 1,
    focusRule: 2,
    indicatorWidth: 4,
    indicatorHeight: 16,
    indicatorGap: 4,
    indicatorLow: 0.35,
    indicatorHigh: 1,
    pulseDuration: 520,
    pulseDelay: 140,
    ease: [0.65, 0, 0.35, 1] as const,
    disabledOpacity: 0.4,
    composerShadowOffset: 2,
    composerShadowOpacity: 0.08,
    composerShadowRadius: 8,
    composerElevation: 3,
  },
  type: {caption: 12, label: 14, body: 15, reading: 16, title: 20},
} as const;
