nodeLinker: hoisted
minimumReleaseAgeExclude:
  - '@assistant-ui/core@0.3.16'
  - '@assistant-ui/react-native@0.1.39'
  - '@assistant-ui/store@0.3.11'
  - '@assistant-ui/tap@0.9.15'
  - '@react-native-async-storage/async-storage@1.21.0'
  - '@react-native-community/netinfo@11.1.0'
  - '@react-native-oh-tpl/async-storage@1.21.0-0.2.2'
  - '@react-native-oh-tpl/netinfo@11.1.0-0.0.8'
  - '@react-native-oh-tpl/react-native-gesture-handler@2.14.17-rc.0'
  - '@react-native-oh-tpl/react-native-safe-area-context@4.7.4-0.2.1'
  - '@react-native-oh-tpl/stack@6.4.0-0.0.4'
  - '@tanstack/react-query@5.102.8'
  - assistant-cloud@0.1.42
  - assistant-stream@0.3.40
  - zod@4.5.4
overrides:
  '@react-native-community/cli': 11.3.6
  '@react-native/codegen': 0.74.0
