import assets from '../rich/generated/assets.json';
export const markdownDocument = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-mobile-markdown'; style-src 'unsafe-inline'; img-src https: http: data:; font-src data:; connect-src 'none'; form-action 'none'; base-uri 'none'"><style>
*{box-sizing:border-box}html,body{margin:0;padding:0;background:transparent;overflow:hidden}body{font:16px/1.65 system-ui;overflow:hidden;overflow-wrap:anywhere}#root{display:flow-root;width:100%}#root>:first-child{margin-top:0}#root>:last-child{margin-bottom:0}p{margin:0 0 12px}h1,h2,h3,h4,h5,h6{line-height:1.35;margin:20px 0 10px}h1{font-size:25px}h2{font-size:22px}h3{font-size:19px}ul,ol{padding-left:24px;margin:10px 0}li{margin:4px 0}li>p{margin:4px 0}blockquote{border-left:3px solid #8ca5ba;padding:4px 12px;margin:12px 0;color:#607585}a{color:#2563a6;text-decoration:underline}code{font-family:monospace;font-size:14px;background:#eaf0f4;border-radius:4px;padding:2px 4px;color:#233544}pre{overflow-x:auto;overflow-y:hidden;white-space:pre;margin:0;padding:12px;background:#f2f5f8}pre code{padding:0;background:none}button{font:inherit;color:#2563a6;background:none;border:0;padding:8px;min-height:40px}.code-block{border:1px solid #cdd8e0;border-radius:8px;overflow:hidden;margin:12px 0}.code-bar{display:flex;justify-content:space-between;align-items:center;padding-left:12px;background:#eaf0f4;color:#435666;font-size:13px}.preview{width:100%;text-align:left}.table-scroll{overflow-x:auto;margin:12px 0}table{border-collapse:collapse;min-width:100%;font-size:14px}td,th{border:1px solid #cdd8e0;padding:8px;text-align:left}th{background:#eaf0f4;color:#233544}img,svg{max-width:100%;height:auto}input[type=checkbox]{margin-right:6px}hr{border:0;border-top:1px solid #cdd8e0;margin:18px 0}.katex-display{overflow-x:auto;overflow-y:hidden;padding:4px 0}.hljs-keyword,.hljs-selector-tag,.hljs-built_in{color:#9c36b5}.hljs-string,.hljs-attr{color:#147d54}.hljs-number,.hljs-literal{color:#b45309}.hljs-comment{color:#667787}
${
  assets.katexCss
}</style></head><body><article id="root"></article><script nonce="mobile-markdown">${assets.markdown.replace(
  /<\/script/gi,
  '<\\/script',
)}</script></body></html>`;
